# Generated by Django 4.1.5 on 2023-01-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_project_user_username_user_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='issue.project'),
        ),
    ]
