# Generated by Django 4.1.5 on 2023-01-27 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_alter_user_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closed_on',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='closed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_issues', to='issue.user'),
        ),
    ]
