# Generated by Django 4.1.5 on 2023-01-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_issue_closed_on_alter_issue_closed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='closed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_issues', to='issue.user'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='closed_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
