# Generated by Django 4.1.5 on 2023-01-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_alter_issue_closed_by_alter_issue_closed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='problem_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
