# Generated by Django 4.1.5 on 2023-01-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_issue_problem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='problem_description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
