# Generated by Django 4.1.5 on 2023-01-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0014_rename_id_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
