# Generated by Django 4.1.5 on 2023-01-31 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0016_alter_issue_closed_by_alter_issue_closed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='closed_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_issues', to='issue.user'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='closed_on',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
